//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Siparis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SIPARIS
    {
        public int SIPARIS_ID { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public Nullable<int> MUSTERI_ID { get; set; }
        public Nullable<decimal> TOPLAM_FIYAT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    
        public virtual TBL_MUSTERI TBL_MUSTERI { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
