//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilyaForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Siparisler
    {
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public string SiparisToplamı { get; set; }
    
        public virtual Tbl_Musteri Tbl_Musteri { get; set; }
    }
}
