//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilyaForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SiparisDetay
    {
        public int ID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public int UrunID { get; set; }
        public Nullable<short> Adet { get; set; }
    
        public virtual Tbl_Urun Tbl_Urun { get; set; }
    }
}
