//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciMVCProje.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BonusOkulEntities : DbContext
    {
        public BonusOkulEntities()
            : base("name=BonusOkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_DERSLER> TBL_DERSLER { get; set; }
        public virtual DbSet<TBL_KULUP> TBL_KULUP { get; set; }
        public virtual DbSet<TBL_NOTLAR> TBL_NOTLAR { get; set; }
        public virtual DbSet<TBL_OGR> TBL_OGR { get; set; }
        public virtual DbSet<TBL_OGRT> TBL_OGRT { get; set; }
        public virtual DbSet<Tbl_Brans> Tbl_Brans { get; set; }
    }
}
