//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciMVCProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Brans
    {
        public Nullable<byte> OGRTID { get; set; }
        public byte DERSID { get; set; }
    
        public virtual TBL_DERSLER TBL_DERSLER { get; set; }
        public virtual TBL_OGRT TBL_OGRT { get; set; }
    }
}
