//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciMVCProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KULUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_KULUP()
        {
            this.TBL_OGR = new HashSet<TBL_OGR>();
        }
    
        public byte KULUP_ID { get; set; }
        public string KULUP_ADI { get; set; }
        public Nullable<short> KULUP_KONT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OGR> TBL_OGR { get; set; }
    }
}
