//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciMVCProje.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OGRT()
        {
            this.Tbl_Brans = new HashSet<Tbl_Brans>();
        }
    
        public byte OGRTID { get; set; }
        public string OGRTAD { get; set; }
        public string OGRTSOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Brans> Tbl_Brans { get; set; }
    }
}
