//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_STOK_TAKIP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SATIS
    {
        public int ID { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public Nullable<short> MUSTERI_ID { get; set; }
        public Nullable<short> PERSONEL_ID { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    
        public virtual TBL_MUSTERI TBL_MUSTERI { get; set; }
        public virtual TBL_PERSONEL TBL_PERSONEL { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
